### ISSUE TITLE
BasicAuth through login form

### ISSUE THREAD

**Issue by manishlok** [simplemvc/skeleton#1]
SimpleMVC is a great start. I found this repo and trying to use it for my project. 
I don't get on how to implement BasicAuth. I made a login form and passed username and password through it. How to make the request and access secret page. Should there be a post route on /secret ?
Could you guide me on how to implement login form for that . Thanks in advance

**Comment by ezimuel** [comment]
@manishlok the `BasicAuth` implements the [Basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) mechanism of HTTP. It uses a simple [authentication](https://github.com/simplemvc/skeleton/blob/main/config/container.php#L23-L26) key in the `config/container.php` file. This is a very basic implementation that I provided only as example on how to setup a controller pipeline in the [route configuration](https://github.com/simplemvc/skeleton/blob/main/config/route.php#L17).

If you want to have a login page and create a protected area in your application, I suggest to send the credentials to a dedicated controller using `POST`. This controller will check if `username` and `password` are valid, you can use a file or a database to store this information. The passwords should be hashed using the [password_hash()](https://www.php.net/manual/en/function.password-hash.php) function of PHP.
I'm planning to add a login page like this in the skeleton application, to show how to use it.

**Comment by ezimuel** [comment]
@manishlok, @fmineo I just released an authentication page using a standard login to access a backend user interface in skeleton ver. [0.2](https://github.com/simplemvc/skeleton/releases/tag/0.2)
