### ISSUE TITLE
How to call the method in config route other than execute?

### ISSUE THREAD

**Issue by kuslahne** [simplemvc/skeleton#3]
I have a problem when call the public method from config route for example:
in fatsroute 

$r->addRoute(['GET','POST','PUT'], '/users', 'User/users');

is there only execute method available?

Regard,
Kus

**Comment by ezimuel** [comment]
@kuslahne yes, the only method executed from a route is `execute()` but you can then route to the specific HTTP methods from there. For instance, you can use the following strategy:
```php
public function execute(
    ServerRequestInterface $request, 
    ResponseInterface $response): ResponseInterface
{
    $method = $request->getMethod();
    if (method_exists($this, $method)) {
        return $this->$method($request, $response);
    }
    return new Response(405, [],  'Method Not Allowed');
}
```
and then have specific `get()`, `post()`, `put()` function to manage the different methods. For instance, this can be the `get()`.
```php
protected function get(
    ServerRequestInterface $request,
    ResponseInterface $response): ResponseInterface
{ 
    // ...
}
```
I'm working on an improved skeleton for SimpleMVC and I used the following `Controller\RouteTrait.php`:
```php
declare(strict_types=1);

namespace App\Controller;

use Nyholm\Psr7\Response;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

trait RouteTrait
{
    public function execute(ServerRequestInterface $request, ResponseInterface $response): ResponseInterface
    {
        $method = $request->getMethod();
        if (method_exists($this, $method)) {
            return $this->$method($request, $response);
        }
        return new Response(
            405,
            [],
            'Method Not Allowed'
        );
    }
}
```
Using that I can then create a Controller that manages multiple HTTP methods just using the Trait. For instance with the following route:
```
[['GET', 'POST'], '/login', Controller\Login::class]
```
you can use a Controller as follows:
```php
class Login implements ControllerInterface
{
    use RouteTrait;

    protected function get(
        ServerRequestInterface $request, 
        ResponseInterface $response): ResponseInterface
    {
        // ...
    }
    protected function post(
        ServerRequestInterface $request, 
        ResponseInterface $response): ResponseInterface
    {
        // ...
    }
```

**Comment by kuslahne** [comment]
Hi @ezimuel,

I have implemented your suggestion. It is pretty neat and it works. 
Thank you for your amazing response.

**Comment by ezimuel** [comment]
@kuslahne thanks, I'm happy if I can be useful. I'm actually considering to add the `RouteTrait` in the [simplemvc/framework](https://github.com/simplemvc/framework) as this can be useful in many projects.
